version: '3.2'
services:
  web:
    build: .
    ports:
      - '2456-2458:2456-2458/udp'
    environment:
      - SERVER_NAME="Valheim Server"
      - SERVER_PASSWORD=""
      - SERVER_WORLD="World"
      - SERVER_PORT=2456
      - SERVER_PUBLIC=1
